export const BALL_CREATE_SUCCESS = 'BALL_CREATE_SUCCESS';
export const BALL_CREATE_FAIL = 'BALL_CREATE_FAIL';

export const BALL_LIST_SUCCESS = 'BALL_LIST_SUCCESS';
export const BALL_LIST_FAIL = 'BALL_LIST_FAIL';
export const BALL_LIST_REQUEST = 'BALL_LIST_REQUEST';

export const BALL_BOOK_SUCCESS = 'BALL_BOOK_SUCCESS';
export const BALL_RETURN_SUCCESS = 'BALL_RETURN_SUCCESS';
export const BALL_ERROR = 'BALL_ERROR';
